FROM node:lts-alpine

WORKDIR /usr/src/app


# COPY package*.json ./
# RUN npm install --production --no-optional && npm cache clean --force

COPY . .

CMD ["tail", "-f"]
# CMD ["npm", "start"]