FROM python:3.9.22-slim

RUN apt-get -q -y update 
RUN apt-get install -y gcc

WORKDIR /usr/src/app

ENV PIP_ROOT_USER_ACTION=ignore

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .