FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04 AS build

WORKDIR /build

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3-dev python3-venv

COPY Backend/requirements.txt .

RUN python3 -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Final stage
FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

WORKDIR /usr/src/app

COPY --from=build /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY Backend/ .

EXPOSE 8080

CMD ["python3", "main.py"]